MusicShare/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
  path('admin/', admin.site.urls),
  path("", include('musicapp.urls')),
  path("login/", include('login.urls')),
]
urlpatterns+=static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

login/urls.py
from django.urls import path
from .views import *

app_name = 'login'

urlpatterns = [
  path('', login_view, name="login"),
  path('logout/', logout_view, name="logout"),
  path('signup/', signup, name="signup"),
]

musicapp/urls.py
from django.urls import path
from .views import *


urlpatterns = [
  path('', index, name='index'),
  path('create/', create, name='create'),
  path('update/<int:id>', update, name='update'),
  path('delete/<int:id>', delete, name='delete'),
  path('mypage/<str:author>', mypage, name='mypage'),
  
]

myproject/myproject/urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
]

login/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

# Create your models here.

musicapp/models.py
from django.db import models

# Create your models here.
class Music(models.Model):
  title=models.CharField(max_length=20)
  content=models.TextField(null=True)
  author=models.CharField(max_length=20)
  datetime=models.DateTimeField(auto_now=True)
  music_title=models.CharField(max_length=20,null=True)
  music_singer=models.CharField(max_length=20,null=True)
  image=models.ImageField(null=True, blank=True)
  
  def __str__(self):
    return self.title

login/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm

class SignUpForm(UserCreationForm):
  password = forms.CharField(
    label="비밀번호를 입력하세요",
    widget=forms.PasswordInput(attrs={'class': 'password-input'}),
  )
  password2 = forms.CharField(
      label="Password confirmation",
      widget=forms.PasswordInput(attrs={'class': 'password-input'}),
  )

  def clean(self):
      cleaned_data = super().clean()
      password1 = cleaned_data.get("password1")
      password2 = cleaned_data.get("password2")

      if password1 and password2 and password1 != password2:
          self.add_error('password2', '비밀번호가 다릅니다.')

      return cleaned_data

login/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth import login, logout
from .forms import SignUpForm

# Create your views here.
def signup(request):
  if request.method == 'GET':
    form = UserCreationForm
    context = {'form' : form}
    return render(request, 'login/signup.html', context)
  
  else:
    form = UserCreationForm(request.POST)

    if form.is_valid():
      instance = form.save()
      return redirect('index')
    else:
      error = "값을 정확히 입력해주세요"
      context = {'form' : form,
                  'error' : error}
      return render(request, 'login/signup.html', context)

    
    
def login_view(request):
  if request.method == 'GET':
    return render(request, 'login/login.html', {'form': AuthenticationForm()})
  
  else:
    form = AuthenticationForm(request, data=request.POST)
    if form.is_valid():
      login(request, form.user_cache)
      return redirect('index')
    else:
      return render(request, 'login/login.html', {'form': form})

def logout_view(request):
  if request.user.is_authenticated:
    logout(request)
  return redirect('index')

musicapp/views.py
from django.shortcuts import render,redirect,get_object_or_404
from django.contrib.auth.decorators import login_required
from .models import Music
from django import forms
from django.http import HttpResponse


def index(request):
  writings=Music.objects.all().order_by('-id')
  return render(request, 'musicapp/index.html', {'writings':writings})

@login_required
def create(request):
  if request.method=="GET":
    return render(request, 'musicapp/create.html')
  else:
    Music.objects.create(
      image = request.FILES.get("image"),
      title=request.POST.get('title'),
      content=request.POST.get('content'),
      music_title=request.POST.get('music_title'),
      music_singer=request.POST.get('music_singer'),
      author=request.user
    )
    return redirect('index')
    
def update(request, id):
  writing=get_object_or_404(Music, pk=id)
  if request.method=="GET":
    return render(request, 'musicapp/update.html', {'writing':writing})
  else:
    writing.title=request.POST.get('title')
    writing.content=request.POST.get('content')
    writing.music_title=request.POST.get('music_title')
    writing.music_singer=request.POST.get('music_singer')
    new_image=request.FILES.get('image')
    if new_image:
      writing.image.delete()
      writing.image=new_image
    writing.save()
    return redirect('mypage',writing.author) 
    
def delete(request, id):
  writing=get_object_or_404(Music, pk=id)
  writing.delete()
  return redirect('mypage',writing.author) 

@login_required
def mypage(request, author):
  try:
    writings = Music.objects.filter(author=author).order_by('-id')
  except Music.DoesNotExist:
    writings = []
  return render(request, 'musicapp/mypage.html', {'writings': writings})



def signup(request):
    if request.method == "POST":
        password1 = request.POST['password1']
        password2 = request.POST['password2']
        res_data={}
        
        if password1 != password2:
            res_data['error'] = '비밀번호가 다릅니다.'
        return render(request, 'signup.html', res_data)

login/templates/login/login.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
    <head>
        <meta charset="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <title>로그인 화면</title>
        <link rel="stylesheet" href="{% static 'css/login_page.css' %}" />
        <style>
            *{
                color: rgba(204, 190, 183, 1);
            }
        </style>
    </head>
    <body>
        <div class="icon">
            <div class="circle">
                <img src="{% static 'media/music-note.png' %}" alt="" />
            </div>
        </div>
        <form action="" method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            <div class="box">
                <div class="email">
                    {{ form.username.label_tag }} {{ form.username }} 
                    {% if form.username.errors %}
                    <ul class="errorlist">
                        {% for error in form.username.errors %}
                        <li>{{ error }}</li>
                        {% endfor %}
                    </ul>
                    {% endif %}

                </div>
                <div class="password">
                    {{ form.password.label_tag }} {{ form.password }} 
                    {% if form.password.errors %}
                    <ul class="errorlist">
                        {% for error in form.password.errors %}
                        <li>{{ error }}</li>
                        {% endfor %}
                    </ul>
                    {% endif %}
                  
                </div>
            </div>
            <div class="putput" style="margin-left: 45%">
                <div style="margin: 10px">
                    <input type="submit" value="Login" />
                </div>
                <div class="signup" style="margin: 10px">
                    <a
                        href="{% url 'login:signup' %}"
                        style="
                            color: rgba(204, 190, 183, 1);
                            text-decoration-line: none;
                        "
                        >회원가입</a
                    >
                </div>
            </div>
        </form>
    </body>
</html>

login/templates/login/login_page.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
    <head>
        <meta charset="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <title>login_page</title>
        <link rel="stylesheet" href="{% static 'css/login_page.css' %}" />
    </head>
    <body>
        <!-- 음악아이콘 -->
        <div class="icon">
            <div class="circle">
                <img src="/music-note.png" alt="" />
            </div>
        </div>

        <!-- id & password box -->
        <div class="box">
            <div class="email">
                <input type="email" name="email" placeholder="ID" />
            </div>
            <div class="password">
                <input type="password" name="password" placeholder="Password" />
            </div>
            <div class="submit">
                <a href="main_page.html">
                    <input type="submit" name="submit" value="Login"
                /></a>
            </div>
        </div>

        <script></script>
    </body>
</html>

login/templates/login/signup.html
<!DOCTYPE html>
{% load static %}
<html lang="ko">
    <head>
        <meta charset="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <title>MusicShare</title>
        <link rel="stylesheet" href="{% static 'css/join_member_page.css' %}" />
    </head>
    <body>
        <form
            action="{% url 'login:signup' %}"
            method="POST"
            enctype="multipart/form-data"
        >
            {% csrf_token %}
            <div class="circle">
                <img
                    src="{% static 'media/music-note.png' %}"
                    class="music_icon"
                />
            </div>
            <p class="main"><b>회원 가입</b></p>
            <fieldset class="field">
                <div class="box2">
                    <br />
                    <label>{{ form.username.label_tag }}</label>
                    <p>{{ form.username }}</p>

                    <label for="password1"
                        >{{ form.password1.label_tag }}</label
                    >
                    <p>{{ form.password1 }}</p>

                    <label for="password2"
                        >{{ form.password2.label_tag }}</label
                    >
                    <p>{{ form.password2 }}</p>

                    {% if error %}
                    <p style="color: rgb(201, 191, 181)">{{error}}</p>
                    {% endif %}
                </div>
            </fieldset>

            <input type="submit" value="가입하기" class="submit" />
            <p class="goto_login">
                이미 계정이 있나요?
                <b><a href="{% url 'login:login' %}">로그인</a></b>
            </p>
        </form>
    </body>
</html>

musicapp/templates/musicapp/create.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" href="{% static 'css/writing_page.css' %}" />
    <link
        rel="stylesheet"
        href="https://use.fontawesome.com/releases/v5.15.4/css/all.css"
        integrity="sha384-DyZ88mC6Up2uqS4h/KRgHuoeGwBcD4Ng9SiP4dIRy0EXTlnuz47vAwmeGwVChigm"
        crossorigin="anonymous"
    />
  <title>Document</title>
  <style>
    #song_list div {
        color: white;
    }

    #song_list hr {
        width: 100%;
    }
</style>
</head>
<body>
    <nav id="menu">
        <a href="{% url 'index' %}"><i class="fas fa-arrow-left"></i></a>
        <p>글작성</p>
    </nav>
  <form action="{% url 'create' %}" method="post" enctype="multipart/form-data">
    {% csrf_token %}


<div id="write">
    <input type="text"  name="title" class="title" placeholder="제목을 입력하세요" />
    <div id="write_con">
        <input type="text" name="content" class="content" placeholder="내용을 입력하세요" />
        <div id="song">
            <div id="write_song">
                <input type="text" name="music_title" class="song_title" placeholder="노래명" />
                <input type="text" name="music_singer" class="singer" placeholder="가수명" />
                <input type="file" name="image" accept="image/*">
                <input type="button" class="add_song" value="&#xf067" onclick="add_song_singer()">
            </div>
            <div id="song_list"></div>
        </div>
    </div>     
</div>
<input type="submit" class="add_write" value="작성완료">
<script>
    function add_song_singer() {
        var songTitle = document.querySelector(".song_title").value;
        var singer = document.querySelector(".singer").value;
        var songList = document.getElementById("song_list");

        var songEntry = document.createElement("div");
        songEntry.textContent = songTitle + " - " + singer;
        songEntry.style.padding = "1rem 0 0 1rem";
        songList.appendChild(songEntry);

        var hrElement = document.createElement("hr");
        hrElement.style.width = "314px";
        songList.appendChild(hrElement);

        songList.style.overflow = "auto";
        songList.style.maxHeight = "317px";
    }
</script>
</body>
</html>

musicapp/templates/musicapp/index.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
    <head>
        <meta charset="UTF-8" />
        <meta http-equiv="X-UA-Compatible" content="IE=edge" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <link rel="stylesheet" href="{% static 'css/index.css' %}" />
        <title>Document</title>
    </head>
    <body>
        <nav>
            <div class="nav_bar">
                <div class="nav_button">
                    <div class="new_create" style="margin: 10px">
                        {% if request.user.is_authenticated %}
                        <a href="{% url 'create' %}"><p>노래 추천하기</p></a>
                        {% endif %}
                    </div>
                    {% if request.user.is_authenticated %}

                    <div class="mypage_btn" style="margin: 10px">
                        <a href="{% url 'mypage' request.user %}"
                            ><p>마이페이지</p></a
                        >
                    </div>
                    <div class="logout_btn" style="margin: 10px">
                        <a href="{% url 'login:logout' %}"><p>로그아웃</p></a>
                    </div>
                    {% else %}
                    <div class="login_button">
                        <a href="{% url 'login:login' %}"> 로그인</a>
                    </div>
                    <div class="join_member_button">
                        <a href="{% url 'login:signup' %}"> 회원가입</a>
                    </div>
                    {% endif %}
                </div>
            </div>
        </nav>
        <div class="title"><h1>음악추천</h1></div>
        {% for writing in writings %}
        <hr />
        <main>
            <div class="main_show">
                <div
                    class="who_author"
                    style="
                        font-size: larger;
                        font-weight: bolder;
                        margin-top: 20px;
                    "
                >
                    작성자 : {{writing.author}}
                </div>
                <div
                    class="img_"
                    style="
                        margin-top: 10px;
                        margin-bottom: 0px;
                        text-align: center;
                    "
                >
                    {% if writing.image %}
                    <img
                        width="200px"
                        height="200px"
                        src="{{writing.image.url}}"
                    />
                    {% else %}
                    <img src="{% static 'media/music_icon.png' %}" alt="" />
                    {% endif %}
                </div>
                <div class="write_box">
                    <div class="writtenbox_1">
                        <div class="element_1">
                            <div class="subject_1">
                                <h3>{{writing.title}}</h3>
                            </div>

                            <div class="box_1">
                                <div class="written_1">{{writing.content}}</div>
                            </div>

                            <div class="song_info_1">
                                <div class="song_1">
                                    <h4>노래 제목 : {{writing.music_title}}</h4>
                                </div>
                                <div class="singer_1">
                                    가수 : {{writing.music_singer}}
                                </div>
                            </div>
                        </div>
                        <div
                            class="date_"
                            style="
                                margin-top: 20px;
                                margin-left: 18%;
                                margin-bottom: 5px;
                            "
                        >
                            {{writing.datetime|date:"Y년 m월 d일"}}
                        </div>
                    </div>

                    <div class="writtenbox"></div>
                </div>
            </div>
        </main>
        {% endfor %}

        <script>
            /*여기 있는 버튼을 작성페이지에 있는 버튼이랑 연결해야함*/
            const button = document.querySelector(".btn button");

            button.addEventListener("click", () => {
                const writtenbox = document.createElement("div");
                writtenbox.className = "writtenbox_new";

                const element = document.createElement("div");
                element.className = "element_new";

                const subject = document.createElement("div");
                subject.className = "subject_new";
                subject.textContent = "제목";

                const box = document.createElement("div");
                box.className = "box_new";

                const written = document.createElement("div");
                written.className = "written_new";

                const songInfo = document.createElement("div");
                songInfo.className = "song_info_new";

                const song = document.createElement("div");
                song.className = "song_new";
                song.textContent = "노래";

                const singer = document.createElement("div");
                singer.className = "singer_new";
                singer.textContent = "가수이름";

                songInfo.appendChild(song);
                songInfo.appendChild(singer);

                box.appendChild(written);

                element.appendChild(subject);
                element.appendChild(box);
                element.appendChild(songInfo);

                writtenbox.appendChild(element);

                document.querySelector(".writtenbox").appendChild(writtenbox);
            });
        </script>
    </body>
</html>

musicapp/templates/musicapp/mypage.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>my_page</title>
    <link rel="stylesheet" href="./my_page.css" />
    <link
      rel="stylesheet"
      href="https://use.fontawesome.com/releases/v5.15.4/css/all.css"
      integrity="sha384-DyZ88mC6Up2uqS4h/KRgHuoeGwBcD4Ng9SiP4dIRy0EXTlnuz47vAwmeGwVChigm"
      crossorigin="anonymous"
    />
    <link rel="stylesheet" href="{% static 'css/mypage.css' %}" />
  </head>
  <body>
    <nav>
        <span class="logout" ><a href="{% url 'index' %}" style="font-size:40px; color:#ccbeb7; text-decoration:none;"><i class="fas fa-arrow-left"></i></a></span>
      <div class="nav-menu">
        
        <span class="logout" ><a href="{% url 'login:logout' %}" style="color:#ccbeb7; text-decoration:none;"><p>로그아웃</p></a></span>
      </div>
    </nav>
    <header>
      <div class="container">
        <p class="title">내가 작성한 글-{{request.user}}</p>
      </div>
    </header>
    {% if not writings %} <h3 style="color:#ccbeb7; text-align:center;margin:20px">작성하신 글이 없습니다.</h3> 
    {% else %} 
    {% for writing in writings %} 
    <section class="sce">
      <div class="container">
        <div>
          <div class="box">
            <div>
              <p class="one_text">{{ writing.title }}</p>
              <p style="text-align:left">{{writing.datetime|date:"Y년 m월 d일"}}</p>
              <div class="commbtn">
                <a href="{% url 'delete' writing.id %}"><button>삭제</button></a>
                <a href="{% url 'update' writing.id %}"><button>수정</button></a>
              </div>
            </div>
          </div>

          
        </div>
      </div>
    </section>
    {% endfor %}
    {% endif %}
  </body>
</html>

musicapp/templates/musicapp/update.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" href="{% static 'css/writing_page.css' %}" />
    <link
        rel="stylesheet"
        href="https://use.fontawesome.com/releases/v5.15.4/css/all.css"
        integrity="sha384-DyZ88mC6Up2uqS4h/KRgHuoeGwBcD4Ng9SiP4dIRy0EXTlnuz47vAwmeGwVChigm"
        crossorigin="anonymous"
    />
  <title>Document</title>
  <style>
    #song_list div {
        color: white;
    }

    #song_list hr {
        width: 100%;
    }
</style>
</head>
<body>
  <nav id="menu">
    <a href="{% url 'mypage' request.user %}"><i class="fas fa-arrow-left"></i></a>
    <p>글작성</p>
  <form action="{% url 'update' writing.pk %}" method="post" enctype="multipart/form-data">
    {% csrf_token %}

</nav>
<div id="write">
    <input type="text"  name="title" class="title" value="{{writing.title}}" placeholder="제목을 입력하세요" />
    <div id="write_con">
        <input type="text" name="content" value="{{writing.content}}" class="content" placeholder="내용을 입력하세요" />
        <div id="song">
            <div id="write_song">
                <input type="text" name="music_title"  value="{{writing.music_title}}" class="song_title" placeholder="노래명" />
                <input type="text" class="singer" name="music_singer" value="{{writing.music_singer}}" placeholder="가수명" />
                {% if writing.image %}
                <p style="font-size:15px">현재 : <a href="{{ writing.image.url }}">{{writing.image.name}}</a></p>
                <p style="font-size:15px"> 변경 : <input type="file" name="image"></p>
              {% else %}
                <input type="file" name="image">
              {% endif %}
                <input type="button"  class="add_song" value="&#xf067" onclick="add_song_singer()">
            </div>
            <div id="song_list"></div>
        </div>
    </div>     
</div>
<input type="submit" class="add_write" value="작성완료">
<script>
    function add_song_singer() {
        var songTitle = document.querySelector(".song_title").value;
        var singer = document.querySelector(".singer").value;
        var songList = document.getElementById("song_list");

        var songEntry = document.createElement("div");
        songEntry.textContent = songTitle + " - " + singer;
        songEntry.style.padding = "1rem 0 0 1rem";
        songList.appendChild(songEntry);

        var hrElement = document.createElement("hr");
        hrElement.style.width = "314px";
        songList.appendChild(hrElement);

        songList.style.overflow = "auto";
        songList.style.maxHeight = "317px";
    }
</script>
</body>
</html>